### PR TITLE
Adopt changes from PR into the exporter script

### PR DESCRIPTION
**Pull request by pudo**
This is trying to replicate #1 inside the script used to generate the `load.cypher` file.

### CODE REVIEW

**Review by jexp — APPROVED** [review]
Looks good!

**Comment by pudo** [comment]
Thanks!

**Comment by pudo** [comment]
Hey @jexp! One weird thing: when I run this query:

```
MATCH (n:name) WHERE count { (n)--() } <= 1 
call { with n
DETACH DELETE (n)
} in transactions of 50000 rows;
```

it's a syntax error: 

```
Invalid input '(': expected ",", ".", "}" or an identifier (line 1, column 30 (offset: 29))
"MATCH (n:name) WHERE count { (n)--() } <= 1"
```

Can I just use `size((n)--()) <= 1` to be equivalent?

**Comment by jexp** [comment]
What version are you using? This should be in 4.4 afaik.

**Comment by pudo** [comment]
Hm, I think 4.4.11. But it works OK with size(), from the looks of it :)

**Comment by jexp** [comment]
But size on patterns is deprecated and will be removed in 5.0 afaik. 

Odd that  count {} doesn’t work on 4.4 yet. It should. Need to check

Sent while on the run

**Pull request merged**
